image: node:10

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm install -g @angular/cli
          - ng test --watch=false
          - ng build --prod --build-optimizer
          - ls -ltr
          - cd dist/weather
          - pipe: atlassian/heroku-deploy:0.1.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              LOCAL_PATH: $(pwd)